### ISSUE TITLE
Minimum password length and Readme update

### ISSUE THREAD

**Issue by danieltayal07** [SpreadSheets600/Password-Manager#13]
Minimum password length requirement and a password strength check. 
Wanted to ensure that generated passwords are not only long but also strong enough to improve security.

1. Added minimum length parameter
2. Added logic to check the strength of the generated password
3. When generating a password, if the password does not meet the strength criteria, the user is notified with a warning message, notifying them to generate a new password.

ALSO,

i have expanded the readme with more user guides and contribution instructions,

-----
Updated --> removed the logic for strength check

if you find this useful please assign me this under hacktoberfest2024,hacktoberfest-accepted

if you don't like it also please tell me what else i can do to contribute if possible!

Thank You!

**Comment by SpreadSheets600** [comment]
@danieltayal07 thank you for this contribution, but the password strength is been looked after @thelegendev it would be great if you could, open up a pr with the rest except the password strength. 

if you wish to help out @thelegendev that would be amazing, ofc if @thelegendev wants any :)

**Comment by danieltayal07** [comment]
sure give me a minute

**Comment by danieltayal07** [comment]
done 
removed the strength checking logic!
