### ISSUE TITLE
New Feature : Import Passwords From Browsers

### ISSUE THREAD

**Issue by SpreadSheets600** [SpreadSheets600/Password-Manager#15]
Well it got a simple concept, all it is need to be done is take the csv file from the browsers when the passwords are exported and put them to the database, or even better take it directly from the browsers .... is it possible ? 🤔

**Comment by iblameRishi** [comment]
Hey @SpreadSheets600 I've made a PR for this, check it out and let me know if anything can be improved!
[PR #17](https://github.com/SpreadSheets600/Password-Manager/pull/17)

**Comment by SpreadSheets600** [comment]
@iblameRishi thank you for this contribution, I will review and merge the PR
